// frontend/src/components/Login.jsx
import { useState } from 'react';

const API_BASE_URL = 'http://localhost:3000';

function Login({ onLoginSuccess, onSwitchToRegister }) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await fetch(`${API_BASE_URL}/login`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ username, password }),
      });

      const data = await response.json();

      if (response.ok) {
        onLoginSuccess({
          username: data.username,
          sessionId: data.sessionId,
        });
      } else {
        setError(data.error || '登入失敗');
      }
    } catch (err) {
      setError('連接失敗，請確認 Backend 是否運行');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-container">
      <h2>登入</h2>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="username">用戶名：</label>
          <input
            type="text"
            id="username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
            placeholder="請輸入用戶名"
          />
        </div>

        <div className="form-group">
          <label htmlFor="password">密碼：</label>
          <input
            type="password"
            id="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            placeholder="請輸入密碼"
          />
        </div>

        {error && <div className="error-message">{error}</div>}

        <button type="submit" disabled={loading} className="submit-btn">
          {loading ? '登入中...' : '登入'}
        </button>
      </form>

      <div className="switch-view">
        <p>還沒有帳號？ <button onClick={onSwitchToRegister} className="link-btn">註冊</button></p>
      </div>
    </div>
  );
}

export default Login;

// frontend/src/components/Login.vue
<template>
  <div class="auth-container">
    <h2>登入</h2>
    <form @submit.prevent="handleSubmit">
      <div class="form-group">
        <label for="username">用戶名：</label>
        <input
          type="text"
          id="username"
          v-model="username"
          required
          placeholder="請輸入用戶名"
        />
      </div>

      <div class="form-group">
        <label for="password">密碼：</label>
        <input
          type="password"
          id="password"
          v-model="password"
          required
          placeholder="請輸入密碼"
        />
      </div>

      <div v-if="error" class="error-message">{{ error }}</div>

      <button type="submit" :disabled="loading" class="submit-btn">
        {{ loading ? '登入中...' : '登入' }}
      </button>
    </form>

    <div class="switch-view">
      <p>還沒有帳號？ <button @click="$emit('switch-to-register')" class="link-btn">註冊</button></p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const API_BASE_URL = 'http://localhost:3000';

const emit = defineEmits(['login-success', 'switch-to-register']);

const username = ref('');
const password = ref('');
const error = ref('');
const loading = ref(false);

const handleSubmit = async () => {
  error.value = '';
  loading.value = true;

  try {
    const response = await fetch(`${API_BASE_URL}/login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        username: username.value,
        password: password.value,
      }),
    });

    const data = await response.json();

    if (response.ok) {
      emit('login-success', {
        username: data.username,
        sessionId: data.sessionId,
      });
    } else {
      error.value = data.error || '登入失敗';
    }
  } catch (err) {
    error.value = '連接失敗，請確認 Backend 是否運行';
  } finally {
    loading.value = false;
  }
};
</script>
