// frontend/src/components/Register.vue
<template>
  <div class="auth-container">
    <h2>註冊</h2>
    <form @submit.prevent="handleSubmit">
      <div class="form-group">
        <label for="username">用戶名：</label>
        <input
          type="text"
          id="username"
          v-model="username"
          required
          placeholder="請輸入用戶名"
        />
      </div>

      <div class="form-group">
        <label for="password">密碼：</label>
        <input
          type="password"
          id="password"
          v-model="password"
          required
          placeholder="請輸入密碼"
        />
      </div>

      <div v-if="error" class="error-message">{{ error }}</div>

      <button type="submit" :disabled="loading" class="submit-btn">
        {{ loading ? '註冊中...' : '註冊' }}
      </button>
    </form>

    <div class="switch-view">
      <p>已有帳號？ <button @click="$emit('switch-to-login')" class="link-btn">登入</button></p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { pushEvent, pushError } from '../instrumentation';

const API_BASE_URL = 'http://localhost:3000';

const emit = defineEmits(['register-success', 'switch-to-login']);

const username = ref('');
const password = ref('');
const error = ref('');
const loading = ref(false);

const handleSubmit = async () => {
  error.value = '';
  loading.value = true;

  try {
    console.log('registering...');
    const response = await fetch(`${API_BASE_URL}/register`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        username: username.value,
        password: password.value,
      }),
    });
    console.log('---- register OK ----');

    const data = await response.json();

    if (response.ok) {
      // 發送註冊成功事件到 Faro
      pushEvent('user_register_success', {
        username: data.username,
        timestamp: new Date().toISOString(),
      });

      alert(`註冊成功！用戶：${data.username}`);
      emit('register-success');
    } else {
      error.value = data.error || '註冊失敗';

      // 發送註冊失敗事件到 Faro
      pushEvent('user_register_failed', {
        username: username.value,
        error: data.error,
        timestamp: new Date().toISOString(),
      });
    }
  } catch (err) {
    error.value = '連接失敗，請確認 Backend 是否運行';

    // 發送錯誤到 Faro
    pushError(err, {
      component: 'Register',
      action: 'register',
      username: username.value,
    });
  } finally {
    loading.value = false;
  }
};
</script>

// frontend/src/components/Register.jsx
import { useState } from 'react';
import { pushEvent, pushError } from '../instrumentation';

const API_BASE_URL = 'http://localhost:3000';

function Register({ onRegisterSuccess, onSwitchToLogin }) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      console.log("registering...")
      const response = await fetch(`${API_BASE_URL}/register`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ username, password }),
      });
      console.log("---- register OK ----")

      const data = await response.json();

      if (response.ok) {
        // 發送註冊成功事件到 Faro
        pushEvent('user_register_success', {
          username: data.username,
          timestamp: new Date().toISOString(),
        });

        alert(`註冊成功！用戶：${data.username}`);
        onRegisterSuccess();
      } else {
        setError(data.error || '註冊失敗');

        // 發送註冊失敗事件到 Faro
        pushEvent('user_register_failed', {
          username,
          error: data.error,
          timestamp: new Date().toISOString(),
        });
      }
    } catch (err) {
      setError('連接失敗，請確認 Backend 是否運行');

      // 發送錯誤到 Faro
      pushError(err, {
        component: 'Register',
        action: 'register',
        username,
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-container">
      <h2>註冊</h2>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="username">用戶名：</label>
          <input
            type="text"
            id="username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
            placeholder="請輸入用戶名"
          />
        </div>

        <div className="form-group">
          <label htmlFor="password">密碼：</label>
          <input
            type="password"
            id="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            placeholder="請輸入密碼"
          />
        </div>

        {error && <div className="error-message">{error}</div>}

        <button type="submit" disabled={loading} className="submit-btn">
          {loading ? '註冊中...' : '註冊'}
        </button>
      </form>

      <div className="switch-view">
        <p>已有帳號？ <button onClick={onSwitchToLogin} className="link-btn">登入</button></p>
      </div>
    </div>
  );
}

export default Register;
